### ISSUE TITLE
Error in map_svg_data.dart class

### ISSUE THREAD

**Issue by Regalbauer** [gi097/flutter_clickable_regions#7]
Hey, 

I am new to flutter. Can you give me some advise please? 

In the _map_svg_data.dart_ class there is an error at the line 8 
`part 'map_svg_data.svg_path.g.dart';`

The error is:
Target of URI hasn't been generated: 'map_svg_data.svg_path.g.dart

How can I handle that? Sorry for that rookie question. 

Thanks in advance

**Comment by mourad-jemail** [comment]
Hello,

**1.** Please update your **pubspec.yaml** as follows:
    1.
`dependencies:`
  `flutter:`
    `sdk: flutter`
  `built_path: ^0.1.0`
  `built_path_annotations: ^0.1.0`
  `built_value: ^8.0.5`

2.
`dev_dependencies:`
  `build_runner: ^1.12.2`
  `built_value_generator: ^8.0.5`

then, in the **Terminal**, run the following command:
`flutter pub get`

After the process is finished, you should be able to generate the 'map_svg_data.svg_path.g.dart' as in the following step.

**2.** In the **Terminal**, please run the following command (as mentioned [here](https://github.com/gi097/flutter_clickable_regions#getting-started)):
`flutter packages pub run build_runner build`

After running that command, you should be able to see the generated file 'map_svg_data.svg_path.g.dart' in your project, under the **lib** folder. That's it.

I hope this helps.

**Comment by gi097** [comment]
As mentioned by @MouradJEMAIL you need to follow the steps provided in the `README.md`. The file you are referring to, is not included in this repository and needs to be generated first.

**Comment by Christian-Valery** [comment]
Hey,

Sorry for comment here but I have some problems about running command `flutter packages pub run build_runner build`.
I'm new to flutter and I want to perform something like in this project.
Below is the error I got. 

`Unhandled exception:
RangeError (end): Invalid value: Not in inclusive range 0..35: -1
#0      RangeError.checkValidRange (dart:core/errors.dart:338:9)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      _parsePackageLocations (package:build_runner_core/src/package_graph/package_graph.dart:162:21)
#3      new PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:67:30)
#4      new PackageGraph.forThisPackage (package:build_runner_core/src/package_graph/package_graph.dart:98:57)
#5      new BuildCommandRunner (package:build_runner/src/entrypoint/runner.dart:20:37)
#6      main (file:///D:/Utilisateurs/Valery/Documents/PROJET/FLUTTER/Projet_Flutter/flutter_windows_2.5.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-0.10.3/bin/build_runner.dart:25:23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
`

And here is my pubspec.yaml:
`environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_path:
  built_path_annotations:
  built_value:

dev_dependencies:
  build_runner:
  built_value_generator:
`

The versions of the different dependencies are on conflict that's why I made them in blank.

Thanks in advance for your help.
